apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" $}}-cluster-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-config
data:
  cluster: |
    ExtIp: 0.0.0.0
    
    ClusterSize: {{ .Values.clusterSize }}

    DiscoverViaDns: false

    EnableTrustedAuth: true

    TrustedRootCertificatesPath: /certs/ca
    CertificateFile: /certs/node/node.crt
    CertificatePrivateKeyFile: /certs/node/node.key
    
  shared: |
    {{ .Values.eventstore.config.shared }}

{{range $i, $e := until (.Values.clusterSize | int) }}
  '{{ include "chart.fullname" $}}-cluster-{{ $i }}': |
    AdvertiseHostToClientAs: {{ (index $.Values.proxy.hosts ($i | toString)) }}
    AdvertiseHttpPortToClientAs: 443
    {{ (index $.Values.eventstore.config ($i | toString)) }}
{{end}}