apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esdb.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esdb.labels" . | nindent 4}}
    app.kubernetes.io/component: proxy
  {{- with .Values.proxy.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  #Will be scaled by setup
  replicas: 0
  selector:
    matchLabels:
      {{- include "esdb.labels" . | nindent 6}}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        {{- include "esdb.labels" . | nindent 8}}
        app.kubernetes.io/component: proxy
      {{- with .Values.proxy.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end }}
    spec:
      serviceAccountName: {{ include "esdb.serviceAccountName" . }}
      {{- with .Values.proxy.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: proxy
          image: {{ .Values.proxy.deployment.image.repository}}:{{.Values.proxy.deployment.image.tag }}
          imagePullPolicy: {{ .Values.proxy.deployment.image.imagePullPolicy }}
          {{- with .Values.proxy.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          env:
            {{- range $i, $e := until (.Values.eventstore.clusterSize | int) }}
            - name: PROXY_EventStore__{{$i}}__PublicHost
              value: {{ index $.Values.proxy.hosts ($i | toString) }}
            - name: PROXY_EventStore__{{$i}}__InternalHost
              value: {{ print (include "esdb.fullname" $) "-cluster-" $i ":2113" }}
            {{- end}}
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /certs/ca
              name: ca-certs
            - mountPath: /tls
              name: tls-cert
          livenessProbe:
            httpGet:
              port: https
              path: /healthz/live
              scheme: HTTPS
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              port: https*/}}
{{/*              path: /healthz/ready*/}}
{{/*              scheme: HTTPS*/}}
              
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.proxy.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end}}
      
      volumes:
        - name: ca-certs
          secret:
            secretName: {{ include "esdb.fullname" .}}-certs
            defaultMode: 0440
            items:
              - key: ca.crt
                path: ca.crt
        - name: tls-cert
          secret:
            secretName: {{ include "helpers.tlssecret" .}}
            defaultMode: 0440
        
          
          
  