apiVersion: v1
kind: Service
metadata:
  name: {{ include "esdb.fullname" $}}-proxy
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "esdb.labels" $ | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "esdb.labels" $ | nindent 4 }}
    app.kubernetes.io/component: proxy