#Default values for eventstoredb deployment
#Ensure that you provide the relevant values for the public URLs

#Configure the eventstore cluster
eventstore:
  clusterSize: 3
  
  #Configure storage for EventStore data
  storage:
    class: premium
    annotations: { }
    size: 100Gi

  image:
    repository: eventstore/eventstore
    #If tag is not provided, then chart [appversion]-bionic will be used
    tag: ""
    pullPolicy: IfNotPresent

  #Custom eventstore config YAML
  #Note that we can use actual YAML here (rather than a string)
  config:
    shared:
      RunProjections: All

    '0': { }
    '1': { }
    '2': { }
    
  logs:
    #If this is disabled, then an emptydir will be mounted for /logs
    #Set to true if you wish to persist logs with a PVC
    persist: false
    storage:
      #By default, the maximum log file size for
      #EventstoreDB is 1 GB
      class: standard
      annotations: {}
      size: 1Gi
  
  #StatefulSet anotations
  annotations: {}
  
  podAnnotations: {}
  
  nodeSelector: {}
  
  terminationGracePeriodSeconds: 120
  
  podSecurityContext:
    #The default eventstore images run as the user eventstore:1000
    fsGroup: 1000
    
  affinity: {}
  
  #Configure the node resource limits
  #resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 250m
  #  limits:
  #    memory: 2Gi
  #    cpu: '2'
  
#Configure the public reverse proxy
proxy:
  
  #Public Node hostnames
  #Note that strange errors will occur if a host is not provided for all cluster nodes
  hosts:
    '0': 'a.esdb.example.com'
    '1': 'b.esdb.example.com'
    '2': 'c.esdb.example.com'
  
  #Configure the ingress resource
  #The ingress must support TLS passthrough for gRPC support
  #The ingress is directed towards https port
  ingress:
    tlsSecretName: ""
    class: ""
    annotations: {}
  
  #Configure the proxy deployment
  deployment:
    replicas: 1
    
    annotations: {}
    
    podAnnotations: {}
  
    nodeSelector: { }

    terminationGracePeriodSeconds: 120
    
    podSecurityContext: {}
    
    #Configure the proxy deployment resource limits
    #resources:
    #  requests:
    #    memory: 64Mi
    #    cpu: 128m
    #  limits:
    #    memory: 512Mi
    #    cpu: 1
    
    affinity: {}
  
    image:
      repository: jeremysv/eventstore-proxy
      tag: latest
      imagePullPolicy: IfNotPresent

#Configure the service account to run under
serviceAccount:
  create: true
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is automatically generated
  name: ""

#Configure the helper CLI images (used by certificate setup job)
cliImages:
  genCerts:
    repository: eventstore/es-gencert-cli
    tag: latest
    pullPolicy: Always
  kubectl:
    repository: bitnami/kubectl
    tag: latest
    pullPolicy: Always

#Configure certificate validity in days
certificatesLength:
  ca: 3650
  node: 3650

imagePullSecrets: { }
