#Default values for eventstoredb deployment
#Ensure that you provide the relevant values for the public URLs

#Configure the eventstore cluster
eventstore:
  clusterSize: 3
  
  storage:
    data:
      class: premium
      annotations: {}
      size: 100Gi
    logs:
      class: premium
      annotations: {}
      size: 100Gi
  
  image:
    repository: eventstore/eventstore
    #If tag is not provided, then chart [appversion]-bionic will be used
    tag: ""
    pullPolicy: IfNotPresent
  
  config:
    #Custom eventstore config YAML. Overrides any values configured by proxy
    shared:
      RunProjections: All
    
    '0': {}
    '1': {}
    '2': {}
  
  #StatefulSet anotations
  annotations: {}
  
  podAnnotations: {}
  
  nodeSelector: {}
  
  terminationGracePeriodSeconds: 120
  
  podSecurityContext:
    #The default eventstore images run as the user eventstore:1000
    fsGroup: 1000
    
  affinity: {}
  
  #Configure the node resource limits
  #resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 250m
  #  limits:
  #    memory: 2Gi
  #    cpu: '2'
  
#Configure the public reverse proxy
proxy:
  
  #Public Node hostnames
  #Note that strange errors will occur if a host is not provided for all cluster nodes
  hosts:
    '0': 'a.esdb.local'
    '1': 'b.esdb.local'
    '2': 'c.esdb.local'
  
  #Configure the ingress resource
  ingress:
    tlsSecretName: ""
    class: ""
    annotations: {}
  
  #Configure the proxy deployment
  deployment:
  
    #Number of replicas for the deployment
    replicas: 1
    
    annotations: {}
    
    podAnnotations: {}
  
    nodeSelector: { }

    terminationGracePeriodSeconds: 120
    
    podSecurityContext: {}
    
    #Configure the proxy deployment resource limits
    #resources:
    #  requests:
    #    memory: 64Mi
    #    cpu: 128m
    #  limits:
    #    memory: 512Mi
    #    cpu: 1
    
    affinity: {}
  
    image:
      repository: jeremysv/eventstore-proxy
      tag: latest
      imagePullPolicy: IfNotPresent

#Configure the service account to run under
serviceAccount:
  create: true
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is automatically generated
  name: ""

#Configure the helper CLI images (used by certificate setup)
cliImages:
  genCerts:
    repository: eventstore/es-gencert-cli
    tag: latest
    pullPolicy: Always
  kubectl:
    repository: bitnami/kubectl
    tag: latest
    pullPolicy: Always

#Configure certificate validity in days
certificatesLength:
  ca: 3650
  node: 3650

imagePullSecrets: { }
