#Default values for eventstoredb deployment
#Ensure to fill the relevant values for the public URLs

#Configure the proxy helper image
cliImages:
  genCerts:
    repository: eventstore/es-gencert-cli
    tag: latest
    pullPolicy: Always
  kubectl:
    repository: bitnami/kubectl
    tag: latest
    pullPolicy: Always
  
#Configure the public reverse proxy
proxy:
  #Node domain names
  hosts:
    "0": 'a.esdb.local'
    "1": 'b.esdb.local'
    "2": 'c.esdb.local'
    
  #Number of replicas for the deployment
  replicas: 1
    
  service:
    #Host to forward acme challenges to (will return a 307)
    #Must be a fully qualified url
    acmeHost: "http://ingress.example.com/"
    annotations: {}
  
  tlsSecretName: ""
  
  #Configure the cert-manager.io/certificate resource
  certificate:
    create: true
    issuer:
      name: default
      kind: ClusterIssuer
      group: cert-manager.io
  
#  #Configure the ingress resource
#  #The ingress controller must support tls passthrough
#  ingress:
#    tlsSecretName: ""
#    
#    class: ""
#    annotations: {}
#    
#    #If class is nginx
#    #annotations:
#    #  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#    #  nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#    #If class is haproxy
#    #annotations:
#    #  kubernetes.io/tls-passthrough: "true"
    
  
  #Deployment annotations
  annotations: {}
  
  podAnnotations: {}

  nodeSelector: { }

  terminationGracePeriodSeconds: 120

  podSecurityContext:
    #The default eventstore images run as the user eventstore:1000
    fsGroup: 1000
  
  #Configure the proxy resource limits
  #resources:
  #  requests:
  #    memory: 64Mi
  #    cpu: 128m
  #  limits:
  #    memory: 512Mi
  #    cpu: 1
  
  image:
    repository: jeremysv/eventstore-proxy
    tag: latest
    imagePullPolicy: IfNotPresent

#Configure the eventstore cluster containers
eventstore:
  clusterSize: 3
  
  storage:
    data:
      class: premium
      annotations: {}
      size: 100Gi
    logs:
      class: premium
      annotations: {}
      size: 100Gi
    
  image:
    repository: eventstore/eventstore
    #If tag is not provided, then chart [appversion]-bionic will be used
    tag: ""
    pullPolicy: IfNotPresent
  
  config:
    #Custom eventstore config YAML. Overrides any values configured by proxy
    shared:
      RunProjections: All
    '0': {}
    '1': {}
    '2': {}
    
  #StatefulSet anotations
  annotations: {} 
  
  podAnnotations: {}
  
  nodeSelector: {}
  
  terminationGracePeriodSeconds: 120
  
  podSecurityContext:
    #The default eventstore images run as the user eventstore:1000
    fsGroup: 1000
  
  
  #Configure the node resource limits
  #resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 250m
  #  limits:
  #    memory: 2Gi
  #    cpu: '2'

#Configure the service account to run under
serviceAccount:
  create: true
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is automatically generated
  name: ""


#Configure certificate validity in days
certificatesLength:
  ca: 3650
  node: 3650

imagePullSecrets: { }
